apiVersion: v1
kind: Service
metadata:
  name: awesome-todo-publisher-srv
spec:
  type: NodePort
  selector:
    app: awesome-todo-publisher
  ports:
    - name: awesome-todo-publisher
      protocol: TCP
      port: 80
      targetPort: 80